#
# Copyright (C) 2017 TQ Systems
#
# Author: Stefan Lange <s.lange@gateware.de>
#
# SPDX-License-Identifier:     GPL-2.0+
#

#obj-y  := tqma57xx.o

obj-$(CONFIG_MBA57XX) += tqma57xx.o
obj-$(CONFIG_MBA57XX) += tqma57xx_mba57xx.o
obj-$(CONFIG_MBa57xx_SQP) += tqma57xx.o
obj-$(CONFIG_MBa57xx_SQP) += tqma57xx_mba57xx_sqp.o
obj-$(CONFIG_CB2P_SQP) += tqma57xx_sqp.o
obj-$(CONFIG_CB2P_SQP) += tqma57xx_cb2p_sqp.o
